apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
    metrics: "true"
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.worker.replicaCount }}
  {{- end }}
  selector:
    matchLabels: { app: worker }
  template:
    metadata:
      labels:
        app: worker
        metrics: "true"
    spec:
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/app/worker"]
          ports:
            - containerPort: {{ .Values.worker.metricsPort }}
          envFrom:
            - configMapRef: { name: app-config }
            - secretRef: { name: app-secret }
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
